version: "3"
   
services:
  rest_api:
    build: .
    restart: always

    depends_on:
      - mongo
    ports:
      - 8000:8000

  mongo:
    image: mongo:5.0

    volumes:
      - surface_interpolator_db:/data/db

  mongo-express:
    image: mongo-express
    ports:
      - 8081:8081
    depends_on: 
      - mongo
volumes:
  surface_interpolator_db:
